version: '3.8'

services:
  ai-agent:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    container_name: ai-agent
